wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715163593.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 23
      4: 3.12.3
      5: 0.16.6
      6: 4.40.1
      8:
      - 1
      - 5
      13: linux-x86_64
